# Generated by Django 5.2 on 2025-04-12 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuzinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_address', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('device_fcm_token', models.CharField(max_length=500)),
                ('customer_secret', models.CharField(max_length=100)),
                ('customer_key', models.CharField(max_length=100)),
                ('passKey', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('expire_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesaAccessToken', to='transactions.buzinessinformation')),
            ],
        ),
    ]
